# Version of docker-compose
version: '3'

# Containers we are going to run
services:
  # Our Phoenix container
  bankapi:
    # The build parameters for this container.
    build:
      # Here we define that it should build from the current directory
      context: .
    environment:
      # Variables to connect to our Postgres server
      DATABASE_URL: "postgres://postgres:postgres@db/apibank"
      SECRET_KEY_BASE: "WCNrLl+zai36i9E/xwbRl/jhZ3hkS7x2XlGZkCZzbsUJYPwp00x5O7wANLUWdsjs"
    ports:
      # Mapping the port to make the Phoenix app accessible outside of the container
      - "4000:4000"
    depends_on:
      # The db container needs to be started before we start this container
      - db
  db:
    # We use the predefined Postgres image
    image: postgres:9.6
    environment:
      # Set user/password for Postgres
      POSTGRES_DB: apibank
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
# Define the volumes
volumes:
  pgdata:

